# Role to allow the service monitor of the Operator to be scraped by the Prometheus instance.
# It must be assigned so that service accounts have the permissions to scrape the metrics of the namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
  namespace: system
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list"]
