apiVersion: apps.console.dev/v1alpha1
kind: ConsoleApplication
metadata:
  name: success
  namespace: avik
  labels:
    app.openshift.io/name: success
spec:
  applicationName: success-app
  git:
    url: https://github.com/digitalocean/sample-nodejs
    contextDir: /
    reference: main
  importStrategy: BuilderImage
  buildConfig:
    builderImage:
      image: nodejs
      tag: 16-ubi8
    buildOption: BuildConfig
    env:
      - name: hello
        value: world
  resourceConfig:
    resourceType: Deployment
    replicas: 3
    env:
      - name: hello
        value: world
    expose:
      targetPort: 3000
      createRoute: true
