on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

name: build-test-lint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true
          check-latest: true
      - name: Set up ko
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: quay.io/openshift-console
      - name: Lint
        run: make lint
      - name: Build
        run: make container-build
      - name: Test
        run: make test
